version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: scooter_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: scooter_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: always

# Можно добавить базу данных (например, PostgreSQL) в дальнейшем
